// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVogRl8U4Y2wX2VluJliDlh1VIIOSISV4',
    appId: '1:180488290427:web:ec19ab93177565674be2de',
    messagingSenderId: '180488290427',
    projectId: 'tcc-app-2022',
    authDomain: 'tcc-app-2022.firebaseapp.com',
    storageBucket: 'tcc-app-2022.appspot.com',
    measurementId: 'G-QC5NDKTD3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6zIXe4H_hq8lVqOCDLJB36kifjPE-oE',
    appId: '1:180488290427:android:ee825b0959493eb54be2de',
    messagingSenderId: '180488290427',
    projectId: 'tcc-app-2022',
    storageBucket: 'tcc-app-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHfjxmh1Mb4IGsi6f2rORDHQijwuWodO0',
    appId: '1:180488290427:ios:97f301ca321a1eb34be2de',
    messagingSenderId: '180488290427',
    projectId: 'tcc-app-2022',
    storageBucket: 'tcc-app-2022.appspot.com',
    iosClientId: '180488290427-t7manbl9fu3m171r0qr0ukcurr8gmdh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHfjxmh1Mb4IGsi6f2rORDHQijwuWodO0',
    appId: '1:180488290427:ios:97f301ca321a1eb34be2de',
    messagingSenderId: '180488290427',
    projectId: 'tcc-app-2022',
    storageBucket: 'tcc-app-2022.appspot.com',
    iosClientId: '180488290427-t7manbl9fu3m171r0qr0ukcurr8gmdh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );
}
