// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-PKwQogUXZxe9odTgXjfULhX7aHl2xxk',
    appId: '1:237626148759:web:84f892082c1e3925e766d2',
    messagingSenderId: '237626148759',
    projectId: 'tcc-igor-fisioapp',
    authDomain: 'tcc-igor-fisioapp.firebaseapp.com',
    storageBucket: 'tcc-igor-fisioapp.appspot.com',
    measurementId: 'G-LMK69K803R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA_5GOA8Xr9570GcN6klnSm19LbhjHsKA',
    appId: '1:237626148759:android:76e40c412f913098e766d2',
    messagingSenderId: '237626148759',
    projectId: 'tcc-igor-fisioapp',
    storageBucket: 'tcc-igor-fisioapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEB8ulRJfwBGAH6MqNzazvBdhcrgLIip4',
    appId: '1:237626148759:ios:2e774fc94be0c39ee766d2',
    messagingSenderId: '237626148759',
    projectId: 'tcc-igor-fisioapp',
    storageBucket: 'tcc-igor-fisioapp.appspot.com',
    androidClientId: '237626148759-7b8s1kam6jkoa6g0b940b7omtt8cvemv.apps.googleusercontent.com',
    iosClientId: '237626148759-c67pltv5m9ncui8qopoe1j7rvrrhmqir.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccFisioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEB8ulRJfwBGAH6MqNzazvBdhcrgLIip4',
    appId: '1:237626148759:ios:2e774fc94be0c39ee766d2',
    messagingSenderId: '237626148759',
    projectId: 'tcc-igor-fisioapp',
    storageBucket: 'tcc-igor-fisioapp.appspot.com',
    androidClientId: '237626148759-7b8s1kam6jkoa6g0b940b7omtt8cvemv.apps.googleusercontent.com',
    iosClientId: '237626148759-c67pltv5m9ncui8qopoe1j7rvrrhmqir.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccFisioApp',
  );
}
