// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIaOreCXDNNfycDzC7fupRCWUyGTYpMMM',
    appId: '1:158965784497:web:11c7e5dd0281ef6d58e790',
    messagingSenderId: '158965784497',
    projectId: 'tccapp2023',
    authDomain: 'tccapp2023.firebaseapp.com',
    storageBucket: 'tccapp2023.appspot.com',
    measurementId: 'G-H4WYCRH5VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tqsLElmNhVk0YALypxdaycw6bldtM9Y',
    appId: '1:158965784497:android:de45821ac8b9aed758e790',
    messagingSenderId: '158965784497',
    projectId: 'tccapp2023',
    storageBucket: 'tccapp2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJweYWk51Xj-7dQWpmoOGEERRoXLJwUrY',
    appId: '1:158965784497:ios:76bcc7cdd5f6beb858e790',
    messagingSenderId: '158965784497',
    projectId: 'tccapp2023',
    storageBucket: 'tccapp2023.appspot.com',
    iosClientId: '158965784497-c2uo4u2dulu0c7hnmboct790qgvlhd1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJweYWk51Xj-7dQWpmoOGEERRoXLJwUrY',
    appId: '1:158965784497:ios:76bcc7cdd5f6beb858e790',
    messagingSenderId: '158965784497',
    projectId: 'tccapp2023',
    storageBucket: 'tccapp2023.appspot.com',
    iosClientId: '158965784497-c2uo4u2dulu0c7hnmboct790qgvlhd1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );
}
